### ISSUE TITLE
Spatial Transformation Optimizations

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#104]
Part of the challenge of migrating to 3D graphics pipeline (i.e. WebGPU) is that the amount of required mathematical calculations increases. Affine transformations and potentially the use of quanternion may result in performance challenges. Consider leveraging either a Rust binding or compute shader for matrix and vector operations. 

**Tasks**
- [ ] Implement Affine Transformations in Python.
- [ ] Review Rust Implementation
- [ ] Evaluate the viability of using compute shaders.

**Rust Implementations**
- [geo](https://docs.rs/crate/geo/latest)
- [caffe2op-affine](https://lib.rs/crates/caffe2op-affine)
- [affine_transforms](https://docs.rs/crate/affine_transforms/latest)

**Compute Shaders**
- [Get started with GPU Compute on the web](https://developer.chrome.com/articles/gpu-compute/)

**Python Transformation Pipeline**
The transformation components are based on the following protocols:
- Ray
- Point
- Vertex
- BBox
- AABBox
- Vector
- Matrix
- Quanternion

A matrix can be applied to: Point | Vertex | BBox | AABBox | Vector | Matrix. 
A quanternion can be applied to: Point | Vertex | BBox | AABBox | Vector | Matrix
