### ISSUE TITLE
Object Preview Mode

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#105]
Create an engine mode designed for previewing game assets. 
The idea is that a model can be viewed like it would be in a game in a isolated capacity.
`lynn preview my_model.obj`

### Expected Behavior
The preview command should determine the appropriate preview based on the file's extension.

| Extension | File Type | Action | 
|-----------|----------|--------|
| wgsl          | Shader.   | Do nothing. Prompt the user to use the shader cmd. |
| obj            | OBJ         | 3D Preview | 
| gltf           | glTF         | 3D Preview | 
| *               | other       | Display help message. | 

### Command Line Options
TBD

### Tasks
- [ ] Add command line option(s).
- [ ] Support the relevant lighting models.
- [ ] Support materials 
- [ ] Support textures.
- [ ] Toggle level of detail meshes.
- [ ] Control camera placement
- [ ] Sky Box
