### ISSUE TITLE
Camera System

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#107]
I need a flexible camera system that enables working in both 2D and 3D.
The simulation design should be able to easily specify what type of camera they want to use.
If the desired camera isn't available they should be able to define one themselves in Python.

**Taxonomy of Projections** (pg 394 of Computer Graphics Using OpenGL by FS Hill, Jr)
Parallel
- Oblique
  - Cavalier
  - Cabinet
- Orthographic
  - Axonometric
    - Isometric
    - Dimetric
    - Trimetric
  - Multiview Orthographic

Perspective
 - One-point
 - Two-point
 - Three-point

For the 2D simulations, using a Parallel camera style may be preferable.

**Tasks**
- [X] Create a new camera class that attempts to model how cameras work.
- [X] Establish a default world camera that renders the 3D scene. 
- [X] Configure the world camera from the scene.json file.
- [x] Create a camera API that enables controlling the camera's attributes.
- [x] Wire up the keyboard and mouse for controlling the camera.
- [x] Establish a default UI orthographic camera that renders the UI.

Camera API Notes
- Need an event based system that enables decoupling I/O events (mouse, keyboard, etc) and controls in the scene. At the moment I've got the ability to define keyboard handlers in the settings.json file.
