### ISSUE TITLE
Forward Rendering Pipeline

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#149]
Create a robust rendering pipeline for v0.2.0 of the engine.

### Characteristics
- [ ] Renders the landscape.
- [ ] Renders multiple agents.
- [ ] Can optionally render vertex normals.
- [ ] Frustum Culling
- [ ] Ambient Lightning (Objects are just visible)
- [ ] Point and Directed Lighting (Objects are lit by lights).

### Rendering Architecture
Renderer Style: [Forward Rendering](https://gamedevelopment.tutsplus.com/forward-rendering-vs-deferred-rendering--gamedev-12342a)

### Render Graphs/Frame Graphs
- [Original Render Graph GDC Talk](https://www.gdcvault.com/play/1024612/FrameGraph-Extensible-Rendering-Architecture-in)
- [Render Graph 101](https://blog.traverseresearch.nl/render-graph-101-f42646255636)
- [Why Talking About Render Graphs](https://logins.github.io/graphics/2021/05/31/RenderGraphs.html)
- [GFX Frame Graph Resources](https://github.com/gfx-rs/gfx/wiki/Frame-graphs)
- [Render graphs and Vulkan — a deep dive](https://themaister.net/blog/2017/08/15/render-graphs-and-vulkan-a-deep-dive/)
- [AMD Render Graph SDK](https://gpuopen.com/learn/rps_1_0/)
- [GDC Talk about AMD's Render Graph SDK](https://gdcvault.com/play/1027922/Advanced-Graphics-Summit-Render-Pipeline)

### Task Graphs
- [ Task Graph Pattern](https://patterns.eecs.berkeley.edu/?page_id=609)
- [Task Graph Renderer at Activision](https://enginearchitecture.org/downloads/reac2023_task_graph_renderer.pdf)

### Resource Allocation & Management
- Ring Allocator
- Linear Allocator

### Bindless Rendering
- [WebGPU Investigation](https://github.com/gpuweb/gpuweb/issues/380)
- [WebGPU Bindless Tracking Issue](https://github.com/gfx-rs/wgpu/issues/3637)
- [Bindless rendering](https://blog.traverseresearch.nl/bindless-rendering-setup-afeb678d77fc)

### Considerations
- Leverage GPU render bundles and draw instance calls. 
- [Javascript Example](https://webgpu.github.io/webgpu-samples/?sample=animometer)
- [WebGPU Render Bundle best practices](https://toji.dev/webgpu-best-practices/render-bundles.html)
- [Z coordinates in WebGPU](https://www.reddit.com/r/webgpu/comments/1ch9ddb/z_coordinates_in_webgpu/)
- [Depth Precision Visualized](https://developer.nvidia.com/content/depth-precision-visualized)

### Other Resources
- [Frame Breakdown of GTA V](https://www.adriancourreges.com/blog/2015/11/02/gta-v-graphics-study/)

**Comment by sholloway** [comment]
GPU Lines

https://arxiv.org/pdf/2405.00127

https://linebender.org/gpu-stroke-expansion-paper/

**Comment by sholloway** [comment]
Consider ways of simplifying  the complexity of working with buffers and uniforms.

The Frame Graph/Render Graph pattern seems like it might be a good fit for what I want to do. 

A thought is have "nodes" that are declared in a similar fashion to data classes but generate the boilerplate of working with buffers an uniforms.

For example, something the like below.
```python
def uniform(cls):
    class Uniform(cls):
        custom_attr = 42
    return Uniform

@uniform
class MyRenderNode:
    pass
``` 

The idea being that the class decorator will dynamically add boilerplate attributes and methods to classes.
See Real Python's article on Metaclasses for other techniques.

**Comment by sholloway** [comment]
## On eventually scaling the engine to enable parallel processing on tasks.

### Current Challenge
A Task in Python is a coroutine. Coroutines cannot be pickled and shared across processes. This is currently a blocker for migrating the existing Task based implementation to work across multiple worker processes. 

### Key Question
Could tasks be defined through the combination of data and function pointers? 
The idea that data that is changing can be serialized and passed between various worker systems in a thread safe way.
Either a function pointer or some other way (magical thinking) of referencing the code to run could be passed around. 

### Exploration
The Task Graph pattern worked well for the simple 2D version of the engine. Things that might help this pattern apply to the 3D engine:
- Adjacency Matrix view of tasks when the sim is paused or running.
- Being able to slow down the engine at run time to watch tasks being executed.
- Graphically visualizing the Task Graph at the various stages of the life cycle. 
- Graphically mapping tasks at design time.
- Having different type of Tasks predefined. 
  (e.g. LoadResource, Compute, AsyncTask, SyncTask, RenderStep, RenderPass, RenderToTarget)
- Have a centralized place to define the task graph for a sim vs the extension mechanism that the 2D engine used. Perhaps a graph focused DSL?
