### ISSUE TITLE
Main Loop and Frame Rate

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#24]
Ensure a stable frame rate.

**Goals**
- Need a budget based approach to frame design.
- Don't maximize the CPU.
- Avoid sleeping threads.
- The frame rate should be appropriate for the screen display. Typically 60 FPS.
- Event driven rather than looping and calling updates on everything.

**Tasks**

- [x] Create a scheduler that can invoke callbacks based on time target.
- [x] Create a priority queue to enable scheduling.
- [x] Support a smooth, steady frame rate. 
- [x] Display the active FPS in a simulation window.
- [ ] 
**Resources** 
- [Game Programming Patterns: Game Loop](https://gameprogrammingpatterns.com/game-loop.html)
- [When should I use Fixed or Variable Time Step](https://gamedev.stackexchange.com/questions/1589/when-should-i-use-a-fixed-or-variable-time-step)
- [Efficient Event-based Simulations](https://www.bleachkitty.com/articles/Effecient,%20Event-Based%20Simulations%20-%20Graham,%20Rez.pdf)
- [Fix your time step](https://gafferongames.com/post/fix_your_timestep/)
- [CPU Slicing](https://thegamedev.guru/unity-performance/cpu-slicing-secrets/)
