### ISSUE TITLE
Single Agent, A* Path Finding

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#3]
Animation loop of an agent calculating a path and then traversing it.
## Todo
- [x] Render a 2D Grid Terrain
- [x] Represent an Agent as a triangle. the tip of the triangle indicates orientation.
- [x] Create an abstraction for actionable paths.
- [ ]  Leverage A* for the agent to calculate a path.
- [x] Animate the agent traversing the path.
- [x] Render with layers. Terrain on one layer, path on a nearer one. Agent on a nearer one.
- [ ] Create a base in Airtable for the simulation/game data? If I do that, how hard will it be to migrate?

## Terrain Thoughts
For the simulator, it should be simple. Not focused on aesthetics. That said, it should enable realistic simulations. 

### Consider Grid vs Hex Grid.
?

### 4 vs 8
The maze used a 4 neighbor strategy. 8 neighbors is reacher and enables diagonal movement.

### Beyond Navigation
What is the world hierarchy imposed by [Dwarf Fortress](https://github.com/DFHack/df-structures)? 
- The DF [Map](https://github.com/DFHack/df-structures/blob/master/df.map.xml) file has a lot of these mappings.
  Need to map is out with LucidChart. 
- The file [world](https://github.com/DFHack/df-structures/blob/master/df.world.xml) might also be useful.
- Biomes?
- A terrain is composed of zones. 
- A Zone is composed of cells?
- A cell: Has an elevation, is or is not navigable, underwater, wet or dry, covered by a tree, rock, machine, structure.

### DearPyGui Drawing API
The coordinate system is right-handed with the x axis point left, y axis point down, and z axis pointing into the screen.
