### ISSUE TITLE
Event Based Game Loop

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#34]
Create an Event Based Game Loop

**Tasks**
- [X] Basic task schedule loop.
- [X] Enforce not pegging the CPU at 100%.
- [X] Calculate and display the running schedule utilization.
- [X] Display the running frame rate.

## EDF
This type of game loop leverages a priority queue to schedule future actions to occur. It is an instance of the [Earliest deadline first (EDF)](https://en.wikipedia.org/wiki/Earliest_deadline_first_scheduling) pattern.

The Basic Loop is of the Form
```python
def main_loop(self, **data):
    previous_time: TimeInMS = TimeUtilities.now()
    lag: TimeInMS = 0

    while self.simulation_state is not SimulationState.ENDED:
      if self.simulation_state is SimulationState.RUNNING:
        current_time: TimeInMS = TimeUtilities.now()
        elapsed_time: TimeInMS = current_time - previous_time
        previous_time = current_time
        lag += elapsed_time

        process_input()

        while lag >= TIME_PER_UPDATE:
          self._scheduler.run(TIME_PER_UPDATE)
          lag -= TIME_PER_UPDATE

        render()
```

**Resources**
- [Game Programming Patterns: Game Loop](https://gameprogrammingpatterns.com/game-loop.html)
- [When should I use Fixed or Variable Time Step](https://gamedev.stackexchange.com/questions/1589/when-should-i-use-a-fixed-or-variable-time-step)
- [Efficient Event-based Simulations](https://www.bleachkitty.com/articles/Effecient,%20Event-Based%20Simulations%20-%20Graham,%20Rez.pdf)
- [Fix your time step](https://gafferongames.com/post/fix_your_timestep/)
- [CPU Slicing](https://thegamedev.guru/unity-performance/cpu-slicing-secrets/)

**Comment by sholloway** [comment]
Perhaps I should add the rolling utilization calculation as the game is running. That'll indicate how much head room the sim has for getting all the work done

**Comment by sholloway** [comment]
Are there existing EDF implementations in Python that I can study?
