### ISSUE TITLE
Multiple Agents Scheduled Simulation

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#38]
Update the existing scheduled simulation to work with multiple agents. 

## Agent Scenarios
- Agents traversing paths.
  - Looping a Path: Agents moving in concentric circles.
  - Agent moving along a path, turning around and going back.
- Scheduled Attribute Changes
  - Change Color based on some function (e.g. sine wave). 
- Agents just spinning around (rotating with no translation). Have multiple agents in a line rotating at different speeds.
- Following: Having multiple agents traverse the same path.

**Tasks**
- [x] Shared Paths: Have 4 agents on the same path, going the same direction.
- [x] Color: Enable agents to have unique colors. 
- [x]  Looping Agents: Have four nested closed paths. Have the agents going in opposite directions and speeds.
- [x] Pacing: Have four agents traverse different paths that are NOT closed. When they get to the end of the path they should reverse their direction and retrace their steps. 
- [x] Agents could have their orientation follow the path or be focused on another point.
- [X] Rotating: Have 4 agents in a cluster that are all simply rotating around their axis. They should rotate at different speeds.
- [X] Color: Enable scheduling color changes. 
- [X] Flashing: Have an agent "flash" their color as a scheduled event.
- [X] Look at using Protocols for handling types and dealing with the renderer function types. I don't like how the simulation context and render layers are defined. Too loose. Passing dictionary objects around sucks. Need to think about patterns like Entity/Component.

**Comment by sholloway** [comment]
Trying to implement this has led to the place of not knowing how to reconcile scheduled based updates vs a traditional update loop. I've started diving deep into trying to identify the appropriate way to organize the agents.
- Entity-Component Pattern (EC)
- Entity Component System Pattern (ECS)

Should the Scheduler be more sophisticated? Look at Naughty Dog's [Job Scheduler Design](https://www.gdcvault.com/play/1022186/Parallelizing-the-Naughty-Dog-Engine) [Slides](http://www.swedishcoding.com/2015/03/08/gdc-2015-presentation-parallelizing-the-naughty-dog-engine/)

**Comment by sholloway** [comment]
Digging into this has left me with a strong feeling of not being organized.
I need to spend more time in diagramming mode before writing any code. 
**Concepts that I need to Flush Out**
- What is a frame?
- Frame Parameters data structure (ala Naughty Dog)
- What is an entity in a simulation. Entity-Component/ECS/Something Else? 
- Should I deal with Jobs that can spawn other jobs (counters). It feels like just scheduling future running ones is too loose.
- Multi-Frame Paradigm?

**Comment by sholloway** [comment]
Dale Weiler's [write up](https://graphitemaster.github.io/fibers/) on implementing a N:M fiber solution is insightful.

In the Python space combining an event loop (e.g. pyuv) with a fiber library like Greenlets or python-fibers may be good enough for my needs.

**TODO**
- [ ] Try spawning nested jobs using python-fibers/greenlets. How flexible are they? Can native python coroutines be used instead?
- [ ] Are there abstractions for dealing with multiple python processes?

**Comment by sholloway** [comment]
Parsers and Generators

Regarding the emergent narrative aspect of this, I wonder if there is a need/opportunity to explore using grammar for crafting the generation of agent behavior, history, or dialogue. 

[EBNF](https://en.m.wikipedia.org/wiki/Extended_Backus–Naur_form) may be good for defining generation rules.
