### ISSUE TITLE
Visual System

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#82]
### Summary
The cognitive agent has the concept of perceiving things around it.
To do this it has a hierarchy of systems. The Nervous System is composed 
of a series of subsystems. Each of which are responsible for detecting 
a specific type of sensation. These sensations are processed by the perception system.

The Visual System shall be responsible for an agent's sight. 

### Tasks
- [x] Create a simulation that demonstrates view frustum culling (detection).
- [x] Define an Agent Frustum. 
- [x] Create a scene renderer that enables viewing agent frustums.
- [x] Update Agent Builder to enable View Frustum TOML configuration.
- [x] Update Agent Builder to enable TOML configuration of Agent systems.
- [x] Create a simulation that demonstrates Agent recognition.

### The Gift of Sight
With sight, there are two main components:
1. Detection: Is the agent aware of anything being there?
2. Recognition: Does the agent know who or what the thing they detected is?

### Detection
Detection is handled via an algorithm that determines line of sight.

Agents have a [view frustum](https://en.wikipedia.org/wiki/Frustum). 
If another agent or entity is in an agent's view frustum and is not 
occluded by anything then it is detected by the agent.

See below for the algorithm.

### Recognition
Just like real people, proximity plays into how agents see. There are two
tiers to what agents can detect and recognize. The ranges of the tiers need 
to be configurable per agent, per simulation. This is to support simulations 
that want agents to have different eye sight capabilities.

- Tier 1: This is within N units of the agent. At this distance the Agent can recognize anything.
- Tier 2: In this range, the agent can identify that the thing being detected is an  agent but 
              cannot recognize who it is.
- Tier3 : Beyond tier 3 things can be detected but not identified. 

### Architectural Considerations
A simulation engine evaluates an agent with this hierarchy of calls.
```python
SimLoop._process_sim_cycle()  # Evaluate one tick of the simulation.
      TaskScheduler.consume().    # Process all of the the queued Tasks for this tick.
        Some Task.process_item()  # A Scene Specific Task loops through all the Agents in a scene.
          Agent.transition_state()     
           Agent.pre_state_change_process_subsystems() # Run all the subsystems
             VisualSystem._before_subsystems_processed_pre_state_change()
               # Runs the detection and recognition algorithm.
               # An agent scans its surroundings and evaluates if it (A) detects
               #  anything and (B) recognizes anything.
```

### Detection Algorithm
The detection algorithm depends on having access to a list of all the agents in the scene
and another list of all the entities in the scene. The active agent is filtered out of the list of agents.
```python
# pseudocode for naive approach
visually_detect(active_agent: Agent, all_other_agents: List[Agent], entities: List[Entity]) -> List[Tuple[Agent, Distance]]:
  possible_agents: List[Agent] = active_agent.view_frustum.intersect(all_other_agents)
  entities_in_frustum: List[Entity] = active_agent.view_frustum.intersect(entities)

  # Does anything occlude an agent?
  detected_agents: List[Agent] = []
  for possible_agent in possible_agents:
    # Find the distance between the two agents.
    agent_distance = distance_between(active_agent, possible_agent) 

    # Cast a ray from the active_agent to the possible_agent.
    # If none of the entities_in_frustum intersect the ray before the agent
    # Then the possible_agent is detected.
    if ray_cast_test(active_agent, possible_agent, entities_in_frustum):
      # Save the detected and distance
      distance = distance(active_agent, possible_agent)
      detected_agents.append((possible_agent, distance))

  return detected_agents
```

### Recognition Algorithm
```python
def recognize(detected_agents: List[Tuple[Agent, Distance]]) -> List[Sensation]:
  sensations: List[Sensation] = []
  for agent, distance in detected_agents:
    if distance <= tier_1_threashold:
      sensations.append(Sensation(SensationType.VisualRecogniztion, agent.id, agent.location))
    elif distance <= tier_2_threashold:
      sensations.append(Sensation(SensationType.VisualDetection, DetectionType.UnknownAgent, agent.location))
    elif distance <= tier_3_threashold: 
      sensations.append(Sensation(SensationType.VisualDetection, DetectionType.UnknownThing, agent.location)) 

  return sensations
```

#### View Frustum
Considerations:
- This should target 2D but be able to extend into 3D.
- The shape type of a Frustum and intersection test should be independent of the Frustum contract.
- The Frustum boundaries is driven by the associated Agent's location, facing vector and other vision related 
   characteristics such as eye sight strength.
- The Frustum should have no knowledge of the Agent protocol or class. The agent should pass information 
   into the Frustum and invoke methods on it.

```python
class ViewFrustum(Generic[Shape], ABC):
  shape: Shape

  def update_frustum(self):
    """Recalculate the frustum boundaries"
    ...

  def intersect(stuff: List[HasIntersectionShape]) -> List[Agent]
    for shape in stuff:
      self.shape.intersect(shape)

class ViewFrustum2D(ViewFrustum)
  ...

class HasIntersectionShape(Protocol):
  def shape(self) -> Shape:
    ...
```

The default 2D frustum is just a triangle.
```python
agent.frustum = ViewFrustum2D[Triangle]()
```

### Proof of Concept Simulation - No Obstructions
I think it will be simpler to develop this if I create a new demo simulation. This simulation will consist of:
1. A central agent that is the focus of the simulation. This agent will be located at the center of the sim
   and will rotate around it's centroid in a clockwise fashion. 
2. Surrounding the central agent will be an array of agents.  

As the sim is running a visual display will say what the agent can see. 

The sim will enable slowing the FPS down using the scene.toml file.

### Proof of Concept Simulation - With Obstructions
A repeat of the above simulation but this time some of agents have entities of different shapes
blocking their view.
