### ISSUE TITLE
Encapsulate DearPyGUI framework.

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#93]
Before migrating to QT or anything else fully encapsulate DearPyGUI.  

**Tasks**

- [ ] Create a UI package.
- [ ] Create a dearpygui module that defines the hooks required to use DearPyGUI.
- [ ] Migrate the code base to use the encapsulation.
