### ISSUE TITLE
Create a WebGPU/QT Prototype

### ISSUE THREAD

**Issue by sholloway** [sholloway/agents-playground#94]

**Comment by sholloway** [comment]
Before getting to far down the road, create a prototype to kick the tires on QT and the Python WebGPU bindings.

**Comment by sholloway** [comment]
**Todo** 

- [x] Create a subproject to nest dependencies. 
- [x] Create a hello world rendering a triangle in 3D. Have the graphical window embedded in a QT window.
- [ ] Enable toggling between graphical full screen and windowed mode.
- [ ] Create a stub application that mimics the existing UI. This doesn't need to be fully functional (i.e. run sims). Rather it should enable the same UI capabilities (e.g. Context Menus, Windows, Modals, Performance Panels, Tooltips, Tables, Copy/Paste, Drag 'n Drop, Mouse Pointer).
